language: java

jdk: oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

install: true

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - bash <(curl -s https://codecov.io/bash)